# Generated by Django 3.0.7 on 2020-07-07 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200707_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_user',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
