# Generated by Django 3.0.7 on 2020-07-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
