# Generated by Django 3.0.7 on 2020-07-02 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('', '')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('', '')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='inner_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='outer_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
