# Generated by Django 3.0.7 on 2020-07-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200702_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('', '')], default='', max_length=10),
        ),
    ]
