# Generated by Django 3.0.7 on 2020-07-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_card_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
