# Generated by Django 3.0.7 on 2020-07-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ash Gray', 'Ash Gray'), ('Gunmetal', 'Gunmetal'), ('Baby Powder', 'Baby Powder'), ('Ivory', 'Ivory'), ('Indigo Dye', 'Indigo Dye')], default='Baby Powder', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('', '')], default='', max_length=100),
        ),
    ]
