# Generated by Django 3.0.7 on 2020-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200703_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ash Gray', 'Ash Gray'), ('Baby Powder', 'Baby Powder'), ('Ivory', 'Ivory'), ('Indigo Dye', 'Indigo Dye'), ('Gunmetal', 'Gunmetal')], default='Baby Powder', max_length=100),
        ),
    ]
