# Generated by Django 3.0.7 on 2020-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200703_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ivory', 'Ivory'), ('Gunmetal', 'Gunmetal'), ('Ash Gray', 'Ash Gray'), ('Indigo Dye', 'Indigo Dye'), ('Baby Powder', 'Baby Powder')], default='Baby Powder', max_length=100),
        ),
    ]
