# Generated by Django 3.0.7 on 2020-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200706_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='message',
            new_name='inner_message',
        ),
        migrations.AddField(
            model_name='card',
            name='outer_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ivory', 'Ivory'), ('Ash Gray', 'Ash Gray'), ('Indigo Dye', 'Indigo Dye'), ('Gunmetal', 'Gunmetal'), ('Baby Powder', 'Baby Powder')], default='Baby Powder', max_length=100),
        ),
    ]
