# Generated by Django 3.0.7 on 2020-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200706_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='inner_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='card',
            name='outer_message',
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Indigo Dye', 'Indigo Dye'), ('Baby Powder', 'Baby Powder'), ('Ash Gray', 'Ash Gray'), ('Gunmetal', 'Gunmetal'), ('Ivory', 'Ivory')], default='Baby Powder', max_length=100),
        ),
    ]
