# Generated by Django 3.0.7 on 2020-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200706_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ash Gray', 'Ash Gray'), ('Gunmetal', 'Gunmetal'), ('Baby Powder', 'Baby Powder'), ('Indigo Dye', 'Indigo Dye'), ('Ivory', 'Ivory')], default='Baby Powder', max_length=100),
        ),
    ]
