# Generated by Django 3.0.7 on 2020-07-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200706_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ivory', 'Ivory'), ('Ash Gray', 'Ash Gray'), ('Baby Powder', 'Baby Powder'), ('Indigo Dye', 'Indigo Dye'), ('Gunmetal', 'Gunmetal')], default='Baby Powder', max_length=100),
        ),
    ]
