# Generated by Django 3.0.7 on 2020-07-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200706_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('groove', 'groove'), ('solid', 'solid'), ('dotted', 'dotted'), ('ridge', 'ridge'), ('none', 'none')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ivory', 'Ivory'), ('Indigo Dye', 'Indigo Dye'), ('Gunmetal', 'Gunmetal'), ('Ash Gray', 'Ash Gray'), ('Baby Powder', 'Baby Powder')], default='Baby Powder', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Libre Baskerville and Source Sans Pro', 'Libre Baskerville and Source Sans Pro'), ('Proza Libre and Open Sans', 'Proza Libre and Open Sans'), ('Lora and Merriweather', 'Lora and Merriweather'), ('BioRhyme and Cabin', 'BioRhyme and Cabin')], default='', max_length=100),
        ),
    ]
