# Generated by Django 3.0.7 on 2020-07-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200707_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('solid', 'solid'), ('ridge', 'ridge'), ('dotted', 'dotted'), ('none', 'none'), ('groove', 'groove')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ash Gray', 'Ash Gray'), ('Indigo Dye', 'Indigo Dye'), ('Ivory', 'Ivory'), ('Gunmetal', 'Gunmetal'), ('Baby Powder', 'Baby Powder')], default='Baby Powder', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Proza Libre and Open Sans', 'Proza Libre and Open Sans'), ('Lora and Merriweather', 'Lora and Merriweather'), ('Libre Baskerville and Source Sans Pro', 'Libre Baskerville and Source Sans Pro'), ('BioRhyme and Cabin', 'BioRhyme and Cabin')], default='', max_length=100),
        ),
    ]
