# Generated by Django 3.0.7 on 2020-07-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200707_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('ridge', 'ridge'), ('groove', 'groove'), ('dotted', 'dotted'), ('solid', 'solid'), ('none', 'none')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Baby Powder', 'Baby Powder'), ('Indigo Dye', 'Indigo Dye'), ('Gunmetal', 'Gunmetal'), ('Ivory', 'Ivory'), ('Ash Gray', 'Ash Gray')], default='Baby Powder', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Libre Baskerville and Source Sans Pro', 'Libre Baskerville and Source Sans Pro'), ('Proza Libre and Open Sans', 'Proza Libre and Open Sans'), ('BioRhyme and Cabin', 'BioRhyme and Cabin'), ('Lora and Merriweather', 'Lora and Merriweather')], default='', max_length=100),
        ),
    ]
