# Generated by Django 3.0.7 on 2020-07-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200707_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('groove', 'groove'), ('solid', 'solid'), ('none', 'none'), ('ridge', 'ridge'), ('dotted', 'dotted')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Gunmetal', 'Gunmetal'), ('Ivory', 'Ivory'), ('Indigo Dye', 'Indigo Dye'), ('Ash Gray', 'Ash Gray'), ('Baby Powder', 'Baby Powder')], default='Baby Powder', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Proza Libre and Open Sans', 'Proza Libre and Open Sans'), ('Libre Baskerville and Source Sans Pro', 'Libre Baskerville and Source Sans Pro'), ('Lora and Merriweather', 'Lora and Merriweather'), ('BioRhyme and Cabin', 'BioRhyme and Cabin')], default='', max_length=100),
        ),
    ]
