# Generated by Django 3.0.7 on 2020-07-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200707_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('groove', 'groove'), ('solid', 'solid'), ('dotted', 'dotted'), ('ridge', 'ridge')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Baby Powder', 'Baby Powder'), ('Ivory', 'Ivory'), ('Indigo Dye', 'Indigo Dye'), ('Gunmetal', 'Gunmetal'), ('Ash Gray', 'Ash Gray')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Proza Libre and Open Sans', 'Proza Libre and Open Sans'), ('BioRhyme and Cabin', 'BioRhyme and Cabin'), ('Libre Baskerville and Source Sans Pro', 'Libre Baskerville and Source Sans Pro'), ('Lora and Merriweather', 'Lora and Merriweather')], default='', max_length=100, null=True),
        ),
    ]
