# Generated by Django 3.0.7 on 2020-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200707_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('Ash Gray', 'Ash Gray'), ('Gunmetal', 'Gunmetal'), ('Baby Powder', 'Baby Powder'), ('Indigo Dye', 'Indigo Dye'), ('Ivory', 'Ivory')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Lora and Merriweather', 'Lora and Merriweather'), ('Proza Libre and Open Sans', 'Proza Libre and Open Sans'), ('Libre Baskerville and Source Sans Pro', 'Libre Baskerville and Source Sans Pro'), ('BioRhyme and Cabin', 'BioRhyme and Cabin')], default='', max_length=100, null=True),
        ),
    ]
