# Generated by Django 3.0.7 on 2020-07-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200707_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(choices=[('groove', 'groove'), ('solid', 'solid'), ('dotted', 'dotted'), ('ridge', 'ridge'), ('none', 'none')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='font',
            field=models.CharField(choices=[('Lora', 'Lora'), ('Merriweather', 'Merriweather'), ('Proza Libre', 'Proza Libre'), ('Open Sans', 'Open Sans'), ('Libre Baskerville', 'Libre Baskerville'), ('Source Sans Pro', 'Source Sans Pro'), ('BioRhyme', 'BioRhyme'), ('Cabin', 'Cabin')], default='', max_length=100, null=True),
        ),
    ]
