# Generated by Django 3.0.7 on 2020-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200709_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='https://bulma.io/images/placeholders/1280x960.png', upload_to=None),
        ),
    ]
