# Generated by Django 3.0.7 on 2020-07-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
